### ISSUE TITLE
Debugger popup throws errors when blocked by browser

### ISSUE THREAD

**Issue by klazuka** [elm/browser#13]
The Elm 0.19 time-traveling debugger cannot be expanded if the browser blocks popups. It throws errors due to an unhandled null. The same configuration works on Elm 0.18, so this appears to be a regression. 

SSCCE: https://gist.github.com/klazuka/b824de5cf1551c1f567c627daa126f81

**Comment by evancz** [comment]
In the future, please unpack the SSCCE into the issue itself. No link to a gist. That makes it easier for me to work with.

Can you dig around with other folks on #elm-dev to get more concrete recommendations about what would be a nice and simple fix? I don't want to add anything new and cool, I just want it to work like 0.18 which did nothing special but I never heard anything about it.

**Comment by klazuka** [comment]
@evancz will do.

I think I've figured out the problem. Apparently popup blocking depends on whether or not you are in an event handler ([source](https://javascript.info/popup-windows)) when you try to open the window. So I compared the callstacks between 0.18 and 0.19 at the time when `window.open()` is called and found a difference.

In 0.18, it's called from `setTimeout` which itself was called from an event handler.
![18 callstack cropped](https://user-images.githubusercontent.com/84525/43430971-a3ee859e-9439-11e8-962f-fe3070731bab.png)

In 0.19, it's called from `requestAnimationFrame` which itself was called from an event handler.
![19 callstack cropped](https://user-images.githubusercontent.com/84525/43430983-b5065604-9439-11e8-8dff-4b7ffeb4b7c8.png)

I couldn't find anything definitive on MDN about popup blocking. But I did find [this StackOverflow answer](https://stackoverflow.com/a/48788436) with some discussion about `setTimeout` working fine but `requestAnimationFrame` causing popups to be blocked.

So I created a [little test program](https://jsbin.com/lexehu/edit?html,output), and sure enough, the popup works in Safari (with popup-blocking enabled) when called by `setTimeout` from an event handler, but does *not* work when called from `requestAnimationFrame`.

----

As for fixing the bug, switching from `requestAnimationFrame` back to `setTimeout` would fix this problem, but I doubt you want to do that. Maybe there's a way to arrange things so that the popup is opened directly in response to the click instead of in the normal `update/view` stepper loop?

**Comment by evancz** [comment]
Excellent work! Thank you!

The click that opens it should be processed by `update`, so it's conceivable to have that run a command that opens it on the click event. Can you figure out a way to test that opening on a click event is alright?

**Comment by klazuka** [comment]
Here's a jsbin that [opens a popup on a click event](https://jsbin.com/mifogiy/edit?html,output).

And here's the details from the HTML5 spec that says that it's ok to open from a click event:
https://www.w3.org/TR/2016/WD-html51-20160310/browsers.html#allowed-to-show-a-popup

**Comment by evancz** [comment]
The new code runs `window.open` when the user clicks. Please test in the next round of binaries and let me know how it goes!

**Comment by klazuka** [comment]
@evancz I just tried it out with the new binaries—the fix worked 👍
