### ISSUE TITLE
page visibility listening doesn't work.

### ISSUE THREAD

**Issue by jessta** [elm/browser#21]
An example of it not working at all.
https://ellie-app.com/37Z8hxpgpK4a1

It looks like the cause is https://github.com/elm/browser/blob/c7f8086fe53852250b84a9991417d81dda22d094/src/Browser/Events.elm#L206 uses a field `info.changes` but  `visibilityInfo` in https://github.com/elm/browser/blob/c7f8086fe53852250b84a9991417d81dda22d094/src/Elm/Kernel/Browser.js#L242 returns an object with a field `change`

**Comment by evancz** [comment]
When you make an SSCCE, can you paste it directly into the issue? Needing to hop around links makes things more difficult.

**Comment by evancz** [comment]
Here is the SSCCE I ended up using:

```elm
import Browser
import Browser.Events exposing (Visibility, onVisibilityChange)
import Html exposing (text)


main : Program () Model Msg
main =
    Browser.element
        { init = \_ -> ([], Cmd.none)
        , view = view
        , update = update
        , subscriptions = \_ -> onVisibilityChange VisibilityChanged
        }

type Msg
  = VisibilityChanged Visibility

update : Msg -> Model -> (Model, Cmd Msg)
update (VisibilityChanged vis) model =
    (vis :: model, Cmd.none)

view : Model -> Html Msg
view model =
    text (Debug.toString model)
```
