### ISSUE TITLE
Error: Could not find any packages named elm/browser.

### ISSUE THREAD

**Issue by songchengen** [elm/browser#23]
Hello, I can not install this package when run `elm package install elm/browser`

I got the message:

```
Error: Could not find any packages named elm/browser.

Here are some packages that have similar names:

    elm-lang/svg
    elm-lang/core
    elm-lang/dom
    elm-lang/mouse

Maybe you want one of those?
```

My `elm-package.json` is:

```
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "5.1.1 <= v < 6.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0",
        "elm-lang/http": "1.0.0 <= v < 2.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}

```

Please help me stupid.

**Comment by brasilikum** [comment]
Hey, this looks like something you can get answered more quickly on the elm slack channel: elmlang.slack.com

This specific error seems to be that elm/browser is for version 0.19 and you are using elm 0.18.

You could run https://github.com/avh4/elm-upgrade which should help you with the transition.

**Comment by evancz** [comment]
Yes, it looks like if you run `elm --version` it would say 0.18 given the stuff you have said here.

Thanks @brasilikum for pointing OP in a good direction. That is great advice!
