### ISSUE TITLE
Missing link in doc of onResize

### ISSUE THREAD

**Issue by Orasund** [elm/browser#25]
the link on the documentation of [onResize](https://package.elm-lang.org/packages/elm/browser/latest/Browser-Events#onResize) goes no [where](https://package.elm-lang.org/packages/elm/browser/latest/TODO).

**Comment by evancz** [comment]
The changes in https://github.com/elm/browser/commit/53e3caa265fd9da3ec9880d47bb95eed6fe24ee6 make it an inline example. There should be a patch release of this library out by Monday for some debugger improvements, so this will go live with that!
