### ISSUE TITLE
Inconsistent cross browser result from Browser.Dom.getViewport

### ISSUE THREAD

**Issue by rl-king** [elm/browser#8]
Safari and Chrome have a different scene.height if content is less than the browsers height

It looks like Safari takes the height of the rendered content if it's less.

## SSCCEE
```elm
module Main exposing (main)

import Browser
import Browser.Dom
import Html exposing (..)
import Task


main : Program () (Maybe Browser.Dom.Viewport) Msg
main =
    Browser.document
        { init = \_ -> ( Nothing, Task.attempt GotViewport Browser.Dom.getViewport )
        , update = update
        , subscriptions = \_ -> Sub.none
        , view = \viewport -> { title = "", body = [ text (Debug.toString viewport) ] }
        }


type Msg
    = GotViewport (Result () Browser.Dom.Viewport)


update : Msg -> Maybe Browser.Dom.Viewport -> ( Maybe Browser.Dom.Viewport, Cmd Msg )
update msg viewport =
    case msg of
        GotViewport (Ok x) ->
            ( Just x, Cmd.none )

        GotViewport _ ->
            ( viewport, Cmd.none )
```

Safari:

```
{ scene = { width = 840, height = 34 }
, viewport = { x = 0, y = 0, width = 840, height = 480 }
}
```

Chrome:

```
{ scene = { width = 840, height = 480 }
, viewport = { x = 0, y = 0, width = 840, height = 480 }
}
```

**Comment by evancz** [comment]
[This article](https://javascript.info/size-and-scroll-window#width-height-of-the-document) recommends:

```javascript
Math.max(
  document.body.scrollHeight, document.documentElement.scrollHeight,
  document.body.offsetHeight, document.documentElement.offsetHeight,
  document.body.clientHeight, document.documentElement.clientHeight
);
```

Justtifictation is:

> Why so? Better don’t ask. These inconsistencies come from ancient times, not a “smart” logic.

My question is "how far back are they trying to support?" I think IE9 is a reasonable "oldest browser" and I don't really want code for things before that. Can anyone find the particular reasons for this recommendation?

**Comment by rl-king** [comment]
Not a direct answer to your questions but jQuery does the same without `document.body.clientHeight` https://github.com/jquery/jquery/blob/master/src/dimensions.js#L31 And they support IE9+.

**Comment by rl-king** [comment]
Observervation:
Rendering this in Safari gives the correct (height of browser window) `document.documentElement.scrollHeight`, although it's the same content as Elm renders
```
<!DOCTYPE html>
<html>
<head><title>sscce</title></head>
<body>
Just { scene = { width = -, height = - }, viewport = { x = - y = -, width = -, height = - } }
</body>
</html>
```
